Packaging updated

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -5,55 +5,30 @@
 
 echo "Running postinst..."
 
-ls /usr/share/slimbookrgbkeyboard
+ls /usr/bin | grep ite8291r3-ctl
 
-sudo rm /home/*/.config/slimbookrgbkeyboard/slimbookrgbkeyboard.conf
-sudo rm /home/*/.config/autostart/slimbookrgbkeyboard-autostart.desktop
-
-ls /usr/local/bin | grep ite8291r3-ctl
-
-if [ $? -ne 0 ]; then #IF Ite not installed
-    echo "Trying to install ite8291r3_driver"
-    pip3 install ite8291r3-ctl
-    if [ $? -eq 0 ];then
-        echo "ite8291r3_driver installed!"
-    else
-        echo "ite8291r3_driver not installed, error"
-    fi
-
-fi
-
-echo "Checking devices"
-/usr/local/bin/ite8291r3-ctl query --devices
-
-if [ $? -eq 0 ]; then #IF device able
-        echo "ite8291r3_driver --> ABLE"
-
+if [ $? -eq 0 ];then
+    echo "ite8291r3_driver installed!"
+    echo "Checking devices"
+    /usr/bin/ite8291r3-ctl query --devices
+    if [ $? -eq 0 ]; then #IF device able
         echo "ite8291r3_driver --> ABLE" > /usr/share/slimbookrgbkeyboard/ite8291r3_driver.txt
-
         echo "Giving exec permissions to system-sleep script"
         chmod +x /usr/lib/systemd/system-sleep/slimbookrgbkeyboard
         
         sudo modprobe qc71_laptop
-        if [ $? -ne 0 ]; then 
-            echo "Installing qc71_laptop"
-            cd /usr/share/slimbookrgbkeyboard/qc71_laptop
-            sudo make dkmsinstall qc71_laptop/0.0
-            sudo modprobe qc71_laptop
-            if [ $? -ne 0 ]; then
-                echo "qc71_laptop modprobe ok"
-            else 
-                echo "qc71_laptop modprobe failed"
-            fi
+        if [ $? -ne 0 ]; then   
+            echo "qc71_laptop modprobe failed"
         else 
             echo "qc71_laptop modprobe ok"
         fi
-
+    else
+        echo "clevo_platform set to install."
+        #This throws clevo-xwmi install when app launched
+        echo "clevo_platform --> TRY ABLE" > /usr/share/slimbookrgbkeyboard/clevo_module.txt
+    fi
 else
-    echo "clevo_platform set to install."
-    #This throws clevo-xwmi install when app launched
-    echo "clevo_platform --> TRY ABLE" > /usr/share/slimbookrgbkeyboard/clevo_module.txt
-
+    echo "ite8291r3_driver not installed, error"
 fi
 
 python3 /usr/share/slimbookrgbkeyboard/src/configuration/check_config.py
